name: Larastan/Pest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  larastan:
    name: Run Larastan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, gd, pdo, sqlite, pdo_sqlite, openssl, curl, fileinfo, intl
          tools: composer

      - name: Install Dependencies
        run: composer install --optimize-autoloader

      - name: Prepare SQLite Database
        run: |
          touch database/database.sqlite
          php artisan migrate --seed
        env:
          DB_CONNECTION: sqlite

      - name: Run Larastan
        run: vendor/bin/phpstan analyse -c phpstan.neon --error-format=github --memory-limit=1G

      - name: Run Pest Tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: sqlite
